//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelInteropGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelInteropGUI.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sheet.
        /// </summary>
        internal static string Add_NewSheet_Text {
            get {
                return ResourceManager.GetString("Add_NewSheet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseBtn_Preset_Text {
            get {
                return ResourceManager.GetString("CloseBtn_Preset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseEditLog_Text {
            get {
                return ResourceManager.GetString("CloseEditLog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        internal static string Col {
            get {
                return ResourceManager.GetString("Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other data is Detected at.
        /// </summary>
        internal static string ContaminationWarning {
            get {
                return ResourceManager.GetString("ContaminationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        internal static string CopyName_Text {
            get {
                return ResourceManager.GetString("CopyName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Selected.
        /// </summary>
        internal static string DataSelected_Text {
            get {
                return ResourceManager.GetString("DataSelected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Preset.
        /// </summary>
        internal static string DeleteBtn_Text {
            get {
                return ResourceManager.GetString("DeleteBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Setting Below.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Preset.
        /// </summary>
        internal static string EditButton_Text {
            get {
                return ResourceManager.GetString("EditButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Preset.
        /// </summary>
        internal static string EditPreset_Text {
            get {
                return ResourceManager.GetString("EditPreset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        internal static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Can&apos;t be Empty.
        /// </summary>
        internal static string EmptyNamePreset {
            get {
                return ResourceManager.GetString("EmptyNamePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected FIle Isn&apos;t Compatible.
        /// </summary>
        internal static string FileIsntCompatible {
            get {
                return ResourceManager.GetString("FileIsntCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string FillinConfirmation {
            get {
                return ResourceManager.GetString("FillinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FillinConfirmationLabel {
            get {
                return ResourceManager.GetString("FillinConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_Label_Text {
            get {
                return ResourceManager.GetString("Language_Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Preset.
        /// </summary>
        internal static string MakePreset_Text {
            get {
                return ResourceManager.GetString("MakePreset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File to be deleted!!.
        /// </summary>
        internal static string NoFiletoDelete {
            get {
                return ResourceManager.GetString("NoFiletoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Finished.
        /// </summary>
        internal static string OperationFinished {
            get {
                return ResourceManager.GetString("OperationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PresetDeleteGroup {
            get {
                return ResourceManager.GetString("PresetDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string PresetLabel_Text {
            get {
                return ResourceManager.GetString("PresetLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Isn&apos;t Selected.
        /// </summary>
        internal static string PresetNotSelected {
            get {
                return ResourceManager.GetString("PresetNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetButton_Text {
            get {
                return ResourceManager.GetString("ResetButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        internal static string Rollback_Text {
            get {
                return ResourceManager.GetString("Rollback.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        internal static string Save_Preset_Button_Text {
            get {
                return ResourceManager.GetString("Save_Preset_Button.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAs_Preset_Label {
            get {
                return ResourceManager.GetString("SaveAs_Preset_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FIle.
        /// </summary>
        internal static string SelectData_Text {
            get {
                return ResourceManager.GetString("SelectData.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sheet.
        /// </summary>
        internal static string SelectSheet_Text {
            get {
                return ResourceManager.GetString("SelectSheet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target.
        /// </summary>
        internal static string SelectTarget_Text {
            get {
                return ResourceManager.GetString("SelectTarget.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButton_Text {
            get {
                return ResourceManager.GetString("SendButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Isn&apos;t Selected.
        /// </summary>
        internal static string SheetNotSelected {
            get {
                return ResourceManager.GetString("SheetNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File not Selected.
        /// </summary>
        internal static string TargetFilenotSelected {
            get {
                return ResourceManager.GetString("TargetFilenotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved data detected.
        /// </summary>
        internal static string UnsavedEdit {
            get {
                return ResourceManager.GetString("UnsavedEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved data won&apos;t be saved.
        /// </summary>
        internal static string UnsavedEditConf {
            get {
                return ResourceManager.GetString("UnsavedEditConf", resourceCulture);
            }
        }
    }
}
